
window = 6 	    #Dynamic window
wall   = 12         #Constant-sized wall
NAME   = c"('mouse', 'rat')"

touch:
	touch Mafft/updated_cds/*
	touch Mafft/mapped_cds/*
.PHONY: touch	


###Include more makefiles
include makeData.mk makeFig.mk
