library(testthat)


testthat::context("Testing process start:")

#Testing material

s1 = "AAT---AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTGAATATAG------ATA------"
s2 = "------AAGTAG---AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT---AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG---CCCAATATTTAATATGATGA---TAG---TAA"

m.2 = "AAT===AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTAATATAG------ATAGTAT===TA"
r.2 = "======TGACAAAATTTGATGCTACATTGGAT---AGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAAATGTAGAT"


####################
#Predicted results

S1 = "AAT===AAACAAAGAATGCTTACTGT---ATAAGGCTTACTGTTCTAGCG---ATCACCGCG---TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTGAATATAG------ATA======"
S2 = "======AAGTAG---AATTTGATGCTACATTGGATGAGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGCCT---AAGAGCCGTTAGATGCGTCGTTG---ATCGCGTCCGATAATTCGGGAGTTG---CCCAATATTTAATATGATGA---TAG===TAA"

M.2 = "AAT===AAACAAAGAATGCTTACTGT===ATAAGGCTTACTGTTCTAGCG===ATCACCGCG===TCATGTCTAGTTATGAACGGC------GGTTTAACATTGAATAGCAAGGCACTTCCATAATAGGGCCGTC---GTAATTGTCTAATATAG======ATAGTAT===TA"
R.2 = "======TGACAAAATTTGATGCTACATTGGAT---AGTCTACTTCGAGCGCGCCGCATCGATTGCAAGAGCAGTGTTGGAAGAGCCGTTAGATGCGTCGTTGTGAATCGCGTCCGATAATTCGGGAGTTGCGCCCCAATATTTAATATGATGATTATAGCTATAAATGTAGAT"


source("../update_gap.R")
Window <<- 6
Wall   <<- 12

#test start_stop_test func.
test_that("Test start_stop_test()",{
  expect_equal(start_stop_test(s1), S1)
  expect_equal(start_stop_test(s2), S2)
})

#test ad_gap_dis func.
test_that("Test ad_gap_dis()",{
  m2 = str_split(as.character(m.2), '')
  r2 = str_split(as.character(r.2), '')
  
  g.m = lapply(m2, function(x) { IRanges(x == '-')})
  g.r = lapply(r2, function(x) { IRanges(x == '-')})
  
  g.m = IRangesList(g.m)[[1]]
  g.r = IRangesList(g.r)[[1]]
  
  expect_equal(ad_gap_dis(g.m, m.2, r.2), c(M.2, R.2))
  
})


