
window = 3 	    #Dynamic window
wall   = 12         #Constant-sized wall
NAME   = c"('mouse', 'rat')"

touch:
	touch Mafft/updated_cds/*
	touch Mafft/mapped_cds/*
.PHONY: touch	


###Include more makefiles
include ../Data_6/makeData.mk ../Data_6/makeFig.mk
