on: push


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.2.1' ]
    name: R ${{ matrix.R }} unitTest
    steps:
      - uses: actions/checkout@v3
      - name: 
        run:  Rscript --vanilla coverage_report.R
        working-directory: Script/tests




