on: push


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.2.1' ]
    name: R ${{ matrix.R }} unitTest
    steps:
      -run:  Rscript --vanilla coverage_report.R
       working-directory: ../../Script/tests




