on: push


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.2.1' ]
    name: R ${{ matrix.R }} sample
    steps:
      - run: Rscript --vanilla ../../Script/tests/coverage_report.R


